export const SDGs = [
    { id: 1, color: "sdg-1", image: "/sdg/goal_1.svg" },
    { id: 2, color: "sdg-2", image: "/sdg/goal_2.svg" },
    { id: 3, color: "sdg-3", image: "/sdg/goal_3.svg" },
    { id: 4, color: "sdg-4", image: "/sdg/goal_4.svg" },
    { id: 5, color: "sdg-5", image: "/sdg/goal_5.svg" },
    { id: 6, color: "sdg-6", image: "/sdg/goal_6.svg" },
    { id: 7, color: "sdg-7", image: "/sdg/goal_7.svg" },
    { id: 8, color: "sdg-8", image: "/sdg/goal_8.svg" },
    { id: 9, color: "sdg-9", image: "/sdg/goal_9.svg" },
    { id: 10, color: "sdg-10", image: "/sdg/goal_10.svg" },
    { id: 11, color: "sdg-11", image: "/sdg/goal_11.svg" },
    { id: 12, color: "sdg-12", image: "/sdg/goal_12.svg" },
    { id: 13, color: "sdg-13", image: "/sdg/goal_13.svg" },
    { id: 14, color: "sdg-14", image: "/sdg/goal_14.svg" },
    { id: 15, color: "sdg-15", image: "/sdg/goal_15.svg" },
    { id: 16, color: "sdg-16", image: "/sdg/goal_16.svg" },
    { id: 17, color: "sdg-17", image: "/sdg/goal_17.svg" },
]
